config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]

  root 'posts#index'

  get 'posts/ranking' => 'posts#ranking'
  get 'posts/random' => 'posts#random'
  
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :bats, only: [:create, :destroy]
    resources :comments do
      resources :outs, only: [:create, :destroy]
    end
  end
  resources :tags do
    get 'posts', to: 'posts#search'
  end
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :bats, dependent: :destroy
    has_many :bated_users, through: :bats, source: :user

    has_many :outs, dependent: :destroy
    has_many :outed_users, through: :outs, source: :user

    mount_uploader :video, VideoUploader
    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
    has_many :post_tag_relations, dependent: :destroy
    has_many :tags, through: :post_tag_relations, dependent: :destroy

    def save_tag(tag_list)
        current_tags = self.tags.pluck(:name) unless self.tags.nil?
        old_tags = current_tags - tag_list
        new_tags = tag_list - current_tags
        # Destroy old taggings:
        old_tags.each do |old_name|
            self.tags.delete Tag.find_by(name: old_name)
        end
        # Create new taggings:
        new_tags.each do |new_name|
            post_tag = Tag.find_or_create_by(name: new_name)
            self.tags << post_tag
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :authenticate_user!, except: [:index, :show]

    def index
        @rank_posts = Post.all.sort {|a,b| b.liked_users.count <=> a.liked_users.count}.first(5)
        if params[:search] != nil && params[:search] != ''
            search = params[:search]
            @posts = Post.where("body LIKE ? OR title LIKE ?", "%#{search}%", "%#{search}%")
        else
            @posts = Post.all
        end
    
    end
    
    def new
        @post = Post.new
    end

    def create
        post = Post.new(post_params)
        post.user_id = current_user.id
        tag_list = params[:post][:name].split(/[[:blank:]]+/).select(&:present?)
        post.user_id = current_user.id
        url = params[:post][:youtube_url] # 取得したい情報を指定
        url = url.last(11)                # 11桁の値(video_id)を取り出し、変数urlに格納
        post.youtube_url = url    
        if post.save
            post.save_tag(tag_list)
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end

    def random
        if params[:search] != nil && params[:search] != ''
            search = params[:search]
            @random_posts = Post.order("RANDOM()").where("body LIKE ? OR title LIKE ?", "%#{search}%", "%#{search}%")
        else
            @random_posts = Post.order("RANDOM()").all
        end 
    end

    def ranking
        if params[:search] != nil && params[:search] != ''
            search = params[:search]
            @rank_posts = Post.where("body LIKE ? OR title LIKE ?", "%#{search}%", "%#{search}%").find(Like.group(:post_id).where(created_at: Time.current.all_week).order('count(post_id) desc').pluck(:post_id))
        else
            @rank_posts = Post.find(Like.group(:post_id).where(created_at: Time.current.all_week).order('count(post_id) desc').pluck(:post_id))
        end 
    end
    
    def search
        @tag = Tag.find(params[:tag_id]) #idに対応したタグのレコードを@tagに代入
        @posts = @tag.posts.all #タグに紐づいた全ての投稿を@postsに代入
    end
    
    def show
        @post = Post.find(params[:id])
        @comments = @post.comments
        @comment = Comment.new
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        post= Post.find(params[:id])
        if post.update(post_params)
        redirect_to :action => "show", :id => post.id
        else
        redirect_to :action => "new"
        end
    end

    def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to action: :index
    end

    private
    def post_params
        params.require(:post).permit(:body,:title,:video,:youtube_url,:image1,:image2,:image3,:image4,:image5,:name)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Linkes</h1>
<h3>編集する</h3>
<p>
<%= form_for @post do |f| %>
    <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, :size => 50 %> 
    </div>
</p>
<p>
    <div class="field">
        <%= f.label :contents %>
        <%= f.text_area :body, :size => "50x10" %>
    </div>
    <div class="field">
        <%= f.label :video %>
        <%= f.file_field :video %>
    </div>
    <div class="field">
        <%= f.label :image1 %>
        <%= f.file_field :image1 %>
    </div>
    <div class="field">
        <%= f.label :image2 %>
        <%= f.file_field :image2 %>
    </div>
    <div class="field">
        <%= f.label :image3 %>
        <%= f.file_field :image3 %>
    </div>
    <div class="field">
        <%= f.label :image4 %>
        <%= f.file_field :image4 %>
    </div>
    <div class="field">
        <%= f.label :image5 %>
        <%= f.file_field :image5 %>
    </div>
    <div class="field">
        <%= f.label :youtube_url %>
        <%= f.text_field :youtube_url%>
    </div>
    <div class="field">
        <%= f.label :tag  %>
        <%= f.text_field :name, :size => 140 %>
    </div>
</p>
    <div>
        <%= f.submit "編集する" %>
    </div>
<% end %>
<%= link_to "投稿一覧に戻る", posts_path %>

app/views/posts/index.html.erb
<h3>投稿一覧</h3>
<%= link_to "新規投稿ページへ", "/posts/new" %>
<li><%= link_to "ランキング", posts_ranking_path %></li>
<li><%= link_to "ランダム", posts_random_path %></li>
<% if user_signed_in? %>
<li><%= link_to "マイページへ", user_path(current_user.id) %></li>
<% end %>


    <div class="posts-container">
        <h1>★投稿</h2>
        <% @posts.each do |t| %>
            <% unless t.bats.count >= 3 %>
            <div class="post">
                <%=  video_tag t.video_url ,:controls => true if t.video?%>
                <%= image_tag t.image1_url, size: "250x200" if t.image1? %>
                <%= image_tag t.image2_url, size: "250x200" if t.image2? %>
                <%= image_tag t.image3_url, size: "250x200" if t.image3? %>
                <%= image_tag t.image4_url, size: "250x200" if t.image4? %>
                <%= image_tag t.image5_url, size: "250x200" if t.image5? %>
                    <div class="youtube_url">
                        <% if t.youtube_url.present? %>
                            <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= t.youtube_url.last(11) if t.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        <% end %>
                    </div>
                <p><big><%= t.title %></big></p>
                <p><%= Rinku.auto_link(t.body, :all, 'target="_blank"').html_safe %></p>
                <a href="/users/<%= t.user.id %>"><%= t.user.username %></a>
                <% if user_signed_in? %>
                    <% if current_user.already_liked?(t) %>
                        <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                            <i class="fas fa-heart"></i><%= t.likes.count %>
                        <% end %>
                    <% else %>
                        <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                            <i class="fas fa-heart"></i><%= t.likes.count %>
                        <% end %>
                    <% end %>
                    <% else %>
                        <i class="fas fa-heart"></i><%= t.likes.count %>
                    <% end %> 

                <% if user_signed_in? %>
                    <% if current_user.already_bated?(t) %>
                        <%= link_to post_bat_path(id: t.id, post_id: t.id), method: :delete do %>
                            <i class="fas fa-thumbs-down"></i>
                        <% end %>
                    <% else %>
                        <%= link_to post_bats_path(id: t.id, post_id: t.id), method: :post do %>
                            <i class="fas fa-thumbs-down"></i>
                        <% end %>
                    <% end %>
                    <% else %>
                            <i class="fas fa-thumbs-down"></i>
                    <% end %> 


                <%= link_to "詳細へ", post_path(t.id) %>
                <% if user_signed_in? && current_user.id == t.user_id %>
                    <%= link_to "編集する", edit_post_path(t.id) %>
                    <%= link_to "削除する", post_path(t.id), method: :delete %>
                <% end %>
            </div>
            <% end %>
        <% end %>
    </div>


        <h2>いいね数ランキング</h2>
                <div class="posts-container">
                    <% @rank_posts.each do |t| %>
                            <div class="post">
                                <%=  video_tag t.video_url ,:controls => true if t.video?%>
                                <%= image_tag t.image1_url, size: "250x200" if t.image1? %>
                                <%= image_tag t.image2_url, size: "250x200" if t.image2? %>
                                <%= image_tag t.image3_url, size: "250x200" if t.image3? %>
                                <%= image_tag t.image4_url, size: "250x200" if t.image4? %>
                                <%= image_tag t.image5_url, size: "250x200" if t.image5? %>
                                    <div class="youtube_url">
                                        <% if t.youtube_url.present? %>
                                            <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= t.youtube_url.last(11) if t.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                        <% end %>
                                    </div>
                                <p><big><%= t.title %></big></p>
                                <p><%= Rinku.auto_link(t.body, :all, 'target="_blank"').html_safe %></p>
                                <a href="/users/<%= t.user.id %>"><%= t.user.username %></a>
                                <% if user_signed_in? %>
                                        <%= link_to "マイページへ", user_path(current_user.id) %>
                                    <% if current_user.already_liked?(t) %>
                                        <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                                            <i class="fas fa-heart"></i><%= t.likes.count %>
                                        <% end %>
                                    <% else %>
                                        <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                                            <i class="fas fa-heart"></i><%= t.likes.count %>
                                        <% end %>
                                    <% end %>
                            <% else %>
                                <i class="fas fa-heart"></i><%= t.likes.count %>
                            <% end %>
                                <%= link_to "詳細へ", post_path(t.id) %>

                                <% if user_signed_in? && current_user.id == t.user_id %>
                                    <%= link_to "編集する", edit_post_path(t.id) %>
                                    <%= link_to "削除する", post_path(t.id), method: :delete %>
                                <% end %>
                            </div>
                    <% end %>
                </div>

app/views/posts/new.html.erb
<h3>新規投稿</h3>
<p>
<%= form_for @post do |f| %>
    <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, :size => 50 %> 
    </div>
</p>
<p>
    <div class="field">
        <%= f.label :contents %>
        <%= f.text_area :body, :size => "50x10" %>
    </div>
    <div class="field">
        <%= f.label :video %>
        <%= f.file_field :video %>
    </div>
    <div class="field">
        <%= f.label :image1 %>
        <%= f.file_field :image1 %>
    </div>
    <div class="field">
        <%= f.label :image2 %>
        <%= f.file_field :image2 %>
    </div>
    <div class="field">
        <%= f.label :image3 %>
        <%= f.file_field :image3 %>
    </div>
    <div class="field">
        <%= f.label :image4 %>
        <%= f.file_field :image4 %>
    </div>
    <div class="field">
        <%= f.label :image5 %>
        <%= f.file_field :image5 %>
    </div>
    <div class="field">
        <%= f.label :youtube_url %>
        <%= f.text_field :youtube_url%>
    </div>
    <div class="field">
        <%= f.label :tag  %>
        <%= f.text_field :name, :size => 140 %>
    </div>
</p>
    <div>
        <%= f.submit "投稿する" %>
    </div>
<% end %>
<%= link_to "投稿一覧に戻る", posts_path %>

app/views/posts/random.html.erb
<h3>投稿一覧</h3>
<li><%= link_to "週間ランキング", posts_ranking_path %></li>
<% if user_signed_in? %>
<li><%= link_to "マイページへ", user_path(current_user.id) %></li>
<% end %>
<li><%= link_to "新規投稿ページへ", "/posts/new" %></li>
<li><%= link_to "投稿一覧", posts_path %></li>


    <div class="posts-container">
        <% @random_posts.each do |t| %>
            <% unless t.bats.count >= 3 %>
            <div class="post">
                <%=  video_tag t.video_url ,:controls => true if t.video?%>
                <%= image_tag t.image1_url, size: "250x200" if t.image1? %>
                <%= image_tag t.image2_url, size: "250x200" if t.image2? %>
                <%= image_tag t.image3_url, size: "250x200" if t.image3? %>
                <%= image_tag t.image4_url, size: "250x200" if t.image4? %>
                <%= image_tag t.image5_url, size: "250x200" if t.image5? %>
                    <div class="youtube_url">
                        <% if t.youtube_url.present? %>
                            <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= t.youtube_url.last(11) if t.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        <% end %>
                    </div>
                <p><big><%= t.title %></big></p>
                <p><%= Rinku.auto_link(t.body, :all, 'target="_blank"').html_safe %></p>
                <a href="/users/<%= t.user.id %>"><%= t.user.username %></a>
                <% if user_signed_in? %>
                    <% if current_user.already_liked?(t) %>
                        <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                            <i class="fas fa-heart"></i><%= t.likes.count %>
                        <% end %>
                    <% else %>
                        <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                            <i class="fas fa-heart"></i><%= t.likes.count %>
                        <% end %>
                    <% end %>
                    <% else %>
                        <i class="fas fa-heart"></i><%= t.likes.count %>
                    <% end %> 

                <% if user_signed_in? %>
                    <% if current_user.already_bated?(t) %>
                        <%= link_to post_bat_path(id: t.id, post_id: t.id), method: :delete do %>
                            <i class="fas fa-thumbs-down"></i>
                        <% end %>
                    <% else %>
                        <%= link_to post_bats_path(id: t.id, post_id: t.id), method: :post do %>
                            <i class="fas fa-thumbs-down"></i>
                        <% end %>
                    <% end %>
                    <% else %>
                            <i class="fas fa-thumbs-down"></i>
                    <% end %> 


                <%= link_to "詳細へ", post_path(t.id) %>
                <% if user_signed_in? && current_user.id == t.user_id %>
                    <%= link_to "編集する", edit_post_path(t.id) %>
                    <%= link_to "削除する", post_path(t.id), method: :delete %>
                <% end %>
            </div>
            <% end %>
        <% end %>
    </div>

app/views/posts/ranking.html.erb
<h3>投稿一覧</h3>
<%= link_to "新規投稿ページへ", "/posts/new" %>
<li><%= link_to "ランダム", posts_random_path %></li>
<li><%= link_to "投稿一覧に戻る", posts_path %></li>
<% if user_signed_in? %>
<li><%= link_to "マイページへ", user_path(current_user.id) %></li>
<% end %>


<h2>いいね数ランキング</h2>
<div class="posts-container">
    <% @rank_posts.each.with_index(1) do |t| %>
            <% unless t.bats.count >= 3 %>
            <div class="post">
                <%=  video_tag t.video_url ,:controls => true if t.video?%>
                <%= image_tag t.image1_url, size: "250x200" if t.image1? %>
                <%= image_tag t.image2_url, size: "250x200" if t.image2? %>
                <%= image_tag t.image3_url, size: "250x200" if t.image3? %>
                <%= image_tag t.image4_url, size: "250x200" if t.image4? %>
                <%= image_tag t.image5_url, size: "250x200" if t.image5? %>
                    <div class="youtube_url">
                        <% if t.youtube_url.present? %>
                            <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= t.youtube_url.last(11) if t.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        <% end %>
                    </div>
                <p><big><%= t.title %></big></p>
                <p><%= Rinku.auto_link(t.body, :all, 'target="_blank"').html_safe %></p>
                <a href="/users/<%= t.user.id %>"><%= t.user.username %></a>
                <% if user_signed_in? %>
                    <% if current_user.already_liked?(t) %>
                        <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                            <i class="fas fa-heart"></i><%= t.likes.count %>
                        <% end %>
                    <% else %>
                        <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                            <i class="fas fa-heart"></i><%= t.likes.count %>
                        <% end %>
                    <% end %>
                    <% else %>
                        <i class="fas fa-heart"></i><%= t.likes.count %>
                    <% end %> 

                <% if user_signed_in? %>
                    <% if current_user.already_bated?(t) %>
                        <%= link_to post_bat_path(id: t.id, post_id: t.id), method: :delete do %>
                            <i class="fas fa-thumbs-down"></i>
                        <% end %>
                    <% else %>
                        <%= link_to post_bats_path(id: t.id, post_id: t.id), method: :post do %>
                            <i class="fas fa-thumbs-down"></i>
                        <% end %>
                    <% end %>
                    <% else %>
                            <i class="fas fa-thumbs-down"></i>
                    <% end %> 


                <%= link_to "詳細へ", post_path(t.id) %>
                <% if user_signed_in? && current_user.id == t.user_id %>
                    <%= link_to "編集する", edit_post_path(t.id) %>
                    <%= link_to "削除する", post_path(t.id), method: :delete %>
                <% end %>
            </div>
            <% end %>
        <% end %>
    </div>

app/views/posts/search.html.erb
<div class= "postsearch">
#<%= @tag.name %>
<% @posts.each do |t| %>
    <div class="post">
        <%= t.body %>
    </div>
<% end %>
</div>
<%= link_to "投稿一覧に戻る", posts_path %>

app/views/posts/show.html.erb
<h3>投稿詳細</h3>
<div class="post">
    <p><big><%= @post.title %></big></p>
    <p><%= Rinku.auto_link(@post.body, :all, 'target="_blank"').html_safe %></p>
    <p><%= @post.created_at %></p>
        <% if user_signed_in? %>
        <% if current_user.already_liked?(@post) %>
            <%= link_to post_like_path(@post), method: :delete do %>
                <i class="fas fa-heart"></i><%= @post.likes.count %>
            <% end %>
        <% else %>
            <%= link_to post_likes_path(@post), method: :post do %>
                <i class="far fa-heart"></i><%= @post.likes.count %>
            <% end %>
        <% end %>
        <% if user_signed_in? %>
        <% if current_user.already_bated?(@post) %>
            <%= link_to post_bat_path(@post), method: :delete do %>
                <i class="fas fa-thumbs-down"></i>
            <% end %>
        <% else %>
            <%= link_to post_likes_path(@post), method: :post do %>
                <i class="fas fa-thumbs-down"></i>
            <% end %>
        <% end %>
        <% else %>
            <i class="fas fa-thumbs-down"></i>
        <% end %> 

    <%=  video_tag @post.video_url ,:controls => true if @post.video?%>
    <%= image_tag @post.image1_url, size: "250x200" if @post.image1? %>
    <%= image_tag @post.image2_url, size: "250x200" if @post.image2? %>
    <%= image_tag @post.image3_url, size: "250x200" if @post.image3? %>
    <%= image_tag @post.image4_url, size: "250x200" if @post.image4? %>
    <%= image_tag @post.image5_url, size: "250x200" if @post.image5? %>
    <% if @post.youtube_url.present? %>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @post.youtube_url.last(11) if @post.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <% end %>
    <% else %>
        <i class="far fa-heart"></i><%= @post.likes.count %>
    <% end %>
    <%= link_to "https://twitter.com/share?url=#{request.url}", title: 'Twitter', target: '_blank' do %>
        <i class="fab fa-twitter" style='color: #3399FF;'></i>
    <% end %>
</div>
<div class="comment-wrapper">
    <p>コメント一覧</p>
    <% @comments.each do |c| %>
        <% unless c.outs.count >= 3 %>
            <%= c.content %>
                <br>
                <%if user_signed_in? %>
                <% if Out.find_by(user_id: current_user.id, post_id: @post.id, comment_id: c.id) %>
                    <%= link_to  post_comment_out_path(@post,c), {class: "like-link", method: :delete } do %>
                    <i class="fas fa-thumbs-down"></i>
                    <% end %>
                <% else %>
                    <%= link_to post_comment_outs_path(@post,c), {class: "like-link", method: :post } do %>
                    <i class="fas fa-thumbs-down"></i>  
                    <% end %>
                <% end %>
            <% else %>
                <i class="fas fa-thumbs-down"></i>
            <% end %>
                <div>
                    <%= c.user.username unless c.user.blank? %>
                    <% if user_signed_in? && current_user.id == c.user_id %>  
                        <%= link_to "削除する", post_comment_path(@post,c), method: :delete %>
                        <%= link_to "編集する", edit_post_comment_path(@post,c) %>
                    <% end %>
                </div>
        <% end %>        
    <% end %>

    <% if user_signed_in? %>
        <%= form_with(model: [@post, @comment], local: true) do |f| %>
        <%= f.text_area :content %>
        <%= button_tag type: "submit" do %>
            <i class="far fa-comments"></i> コメントする
        <% end %>
        <% end %>
    <% end %>

    <% @post.tags.each do |tag| %>
        #<span><%= tag.name %></span>
    <% end %>
</div>


<%= link_to "投稿一覧に戻る", posts_path %>
<% if user_signed_in? && current_user.id == @post.user_id %>
    <%= link_to "編集する", edit_post_path(@post.id) %>
<% end %>
